### ISSUE TITLE
Create about us page

### ISSUE THREAD

**Issue by riadhmouamnia** [202306-NEA-DZ-FEW/movie-project-popcornpalace#27]
1. Create and design a card for each member
2. For each member display a card

About Us page should contain information about each member on a card

**Comment by mohamed70601** [comment]
Done [d302069](https://github.com/202306-NEA-DZ-FEW/movie-project-popcornpalace/commit/d302069a99bd2eac54f4f08dd611617b2f6f1d3c)

**Comment by riadhmouamnia** [comment]
well done
